### PR TITLE
feat: "Add screenshot" button on local cuke reports

### PR DESCRIPTION
**Pull request by ksentak**
This PR adds custom logic to the cucumber reporting templates to add an "Add Screenshot" button to locally generated cucumber reports.

### CODE REVIEW

**Review by jbigel — DISMISSED** [review]

**Comment by mhughesacn** [comment]
Hi Keaton: I am getting code matches in generic.js as well.  Please will you add a comment under the Comcast header to say that it:

```
Adapts material from multiple-cucumber-html-reporter which is:
 Copyright (c) 2023 Wasiq Bhamla
 Licensed under the MIT License
```

so that the credit is clear here too.  Thank you!

**Comment by ksentak** [comment]
Hi @mhughesacn, I have added the requested comment. Please let me know if there is anything else I need to do in order for scans to pass on this pull request. Thanks in advance!

**Review by jbigel — APPROVED** [review]

**Comment by mhughesacn** [comment]
Thanks Keaton

**Pull request merged**
